export const PITT_DIVERS = [
  { id: "pitt-ad", name: "Ayla Debowsky" },
  { id: "pitt-cc", name: "Cameron Cash" },
  { id: "pitt-cg", name: "Cassandra Guerrera" },
  { id: "pitt-cm", name: "Chase Marafioto" },
  { id: "pitt-df", name: "Daley Fraser" },
  { id: "pitt-dr", name: "Dylan Reed" },
  { id: "pitt-eg", name: "Emma Gravgaard" },
  { id: "pitt-er", name: "Ethan Radio" },
  { id: "pitt-hp", name: "Hannah Polosky" },
  { id: "pitt-js", name: "Jackson Salisbury" },
  { id: "pitt-jv", name: "Jess Vega" },
  { id: "pitt-jb", name: "Jocelyn Brooks" },
  { id: "pitt-jp", name: "Joshua Parquet" },
  { id: "pitt-jom", name: "Juan Osorio Mendoza" },
  { id: "pitt-mf", name: "Margaret Foley" },
  { id: "pitt-mom", name: "Mariana Osorio Mendoza" },
  { id: "pitt-mi", name: "Megan Iannon" },
  { id: "pitt-mg", name: "Meredith Gould" },
  { id: "pitt-nk", name: "Nathaniel Keller" },
  { id: "pitt-nb", name: "Noah Bernard" },
  { id: "pitt-nm", name: "Noah Marble" },
  { id: "pitt-rd", name: "Rachel Dickerson" },
];
